### PR TITLE
Add Meson build system

### PR DESCRIPTION
**Pull request by nana-4**
This PR adds Meson build system to the project :rocket:

### CODE REVIEW

**Comment by nana-4** [comment]
TODO:

- [ ] Fix gnome-shell symlinks
- [ ] Add missing `COPYING` to the build
- [ ] Review SCSS/CSS build
- [ ] Review version check of gnome-shell
- [ ] Add version check for cinnamon? (It's not mandatory at the moment)
- [ ] Add a build option `gtk2_hidpi`? (or more common `hidpi`?)

**Comment by nana-4** [comment]
This is still a WIP, but most of this is pretty finished.

Since I'm new to Meson, I'd highly appreciate any reviews from anyone. Any trivial comments, reviews, and suggestions are very welcome :)

**Comment by nana-4** [comment]
The most unsure thing here for me is the SCSS configuration, CSS generation, renaming, and installation in `foreach` on `src/{cinnamon,gtk,gnome-shell}/sass/meson.build`. It could probably be improved, but I have no better idea for now...

**Comment by gsbhasin123** [comment]
Honestly I'm not sure about the scss, but everything else looks good!
> The most unsure thing here for me is the SCSS configuration, CSS generation, renaming, and installation in foreach on src/{cinnamon,gtk,gnome-shell}/sass/meson.build. It could probably be improved, but I have no better idea for now...

What is wrong with that though?

**Comment by actionless** [comment]
just please check if `change_color.sh` still produces an expected result before merging this one ^__^

**Comment by nana-4** [comment]
I think this is ready to be merged now.

**Comment by nana-4** [comment]
Merged.

If you find problems, please let me know. Those should be addressed in later commits.

**Comment by actionless** [comment]
so, in case of using install.sh meson is not used and i don't have to add as the new deps for materia plugin?

initially i thought you gonna use install.sh to just wrap meson config

**Comment by nana-4** [comment]
@actionless Yes, I originally intended to keep `install.sh` without Meson so that older distros that don't ship Meson >= 0.47 still can install latest Materia. Sorry for confusing you :sweat_smile: 

But if you don't mind adding new dependencies, `meson >= 0.47` & `ninja`, we probably could use meson in `change_color.sh`.

**Comment by actionless** [comment]
it's for sure shouldn't be a problem with arch linux packaging, but i'm not sure about the rest of the distros and flatpak, especially as in flatpak you don't have normal package management

**Comment by nana-4** [comment]
Sure...

**Comment by nana-4** [comment]
FYI, the `meson` package in Ubuntu 18.04 repository is [version 0.45.1](https://packages.ubuntu.com/ja/bionic-updates/meson). If you want to run Oomox on such an older distro, I think we should not switch to meson in `change_color.sh`.

**Comment by actionless** [comment]
currently the minimal supported ubuntu version for oomox is 17.04, however i'm not sure what the materia gtk theme itself would work fine at a such old gtk version: https://github.com/themix-project/oomox/blob/master/packaging/ubuntu/control

**Comment by nana-4** [comment]
Materia theme supports GTK >= 3.20. According to [distrowatch](https://distrowatch.com/table.php?distribution=ubuntu), Materia (and the oomox plugin) should work at least on Ubuntu 16.10 or later.

**Comment by actionless** [comment]
16.10 doesn't have sassc, it appeared in ubuntu repos only starting from 17.04

**Comment by actionless** [comment]
currently oomox have two ubuntu packages, `17.04..18.04` and `18.10+`

it seems what first one will be still maintained til 2023:

https://wiki.ubuntu.com/BionicBeaver/ReleaseNotes
> The 'main' archive of Ubuntu 18.04 LTS will be supported for 5 years until April 2023.

**Comment by nana-4** [comment]
Ah, right, thanks for clarifying. So we probably should not switch to meson in `change_color.sh` for those older distros then.

**Comment by nana-4** [comment]
P.S. Just FYI, I just removed the `bc` dependency from the theme in d76a33b21dda2600ddfcdb45741d4c7e08f3bfbb :)

**Comment by actionless** [comment]
> P.S. Just FYI, I just removed the bc dependency from the theme in d76a33b :)

i see not fully yet:

```
$ grep --include '*.sh' bc * -R
scripts/darker.sh:  result="$(bc <<< "ibase=16; $value - $light_delta")"
scripts/mix.sh:  result="$(bc <<< "scale=0; ($value1 * 100 * $ratio + $value2 * 100 * (1 - $ratio)) / 100")"
```

**Comment by nana-4** [comment]
Oh, I forgot about those scripts. Sorry!

**Pull request merged**
