### PR TITLE
Update Gnome-shell calendar design

### PR DESCRIPTION
**Pull request by TomBursch**
Fixed a bug where the dark theme used dark text colors and improved design somewhat based on [Material picker component](https://material.io/components/pickers/)

Screenshot

### CODE REVIEW

**Comment by actionless** [comment]
why SVG instead of just background/border/border-radius in CSS?

**Comment by nana-4** [comment]
Thanks for the PR, @TomBursch :)

> a bug where the dark theme used dark text colors

Really? What version of gnome-shell are you using? Can you provide a screenshot?

Some quick comments for the PR:

- I like the idea of using dot SVG for `.calendar-day-with-events` (I actually had that plan :)), but I would prefer using the bule primary color over the gray color for it. Also, that SVG looks blurry because its size doesn't match the element. Some size adjustments are needed here.
- I would prefer `$stroke` color for  border-color of `.calendar-today`.
- For some reason `.calendar-today` doesn't look like a perfect circle. Needs to be fixed.

**Comment by nana-4** [comment]
@actionless Unfortunately, we can't use pure CSS here for such design in gnome-shell :(

**Comment by nana-4** [comment]
I'm trying to make some fixes and adjustments based on your PR. Maybe we should use a non-translucent primary color for selected items here as per the Material picker guideline.

image

**Comment by TomBursch** [comment]
Thanks for the feedback, I knew it needed some more work :).
I had the non-translucent color initially but didn't know if it's a welcome change. That's also why I was using grey for the event dots.

About the bug, I'm using GNOME Shell 3.34.3, and the calendar looks like this:
Screenshot

**Comment by nana-4** [comment]
My apologies for the late reply.

I made the design changes myself based on your work, with some corrections. Thanks again for your contribution.

**Comment by nana-4** [comment]
Unfortunately, I still can't reproduce the dark text problem. Can you reproduce your problem with the default theme? I'm guessing your problem comes from one of the following:

- your extension
- your own `~/.config/gnome-shell/gnome-shell.css` file
- the [unsupported](https://github.com/nana-4/materia-theme#unsupported) "Ubuntu" session or "Pop" session, if you're using Ubuntu or Pop.

If none of these apply and you still have the problem with the latest `master` branch, please let me know. Thanks!

**Pull request closed without merging**
