### PR TITLE
new ./install.sh (normal installation options only)

### PR DESCRIPTION
**Pull request by n3oxmind**
This script will install Materia theme based on the user preferences.
features:
- Robust and will not run unless all the options checked first.
- Support all [color,size] variants, but installing only the standard not supported yet (easy to do will fix it later)
- Simple and easy to use.

note: `usage` may need to be updated.
Please test it and try to break it and let me know.

### CODE REVIEW

**Comment by nana-4** [comment]
Hi @n3oxmind,
I appreciate your understanding and fine work.

Before reviewing this, I have one question:

Was it bad for you to simply improve [my revised version](https://github.com/nana-4/materia-theme/blob/improve-install-sh/install.sh)? In my opinion, it is better and simpler to [lump install items together as an function](https://github.com/nana-4/materia-theme/blob/960249da9859908a09f84fa0e499857a7dc6f74c/install.sh#L47-L116) than to [separate them](https://github.com/n3oxmind/materia-theme/blob/c2c21744602818b1ab10685a818f1ae1be230c84/install.sh#L100-L210). What do you think?

---

About this script, I've noticed two issues. (In [my version](https://github.com/nana-4/materia-theme/blob/improve-install-sh/install.sh) both are feasible, btw.)

1. How can I install all the variants at once with the script? In my opinion, it would be better to install all the variants without any options. (just `sudo ./install.sh`)

2. `./install.sh --color light dark` doesn't seem to work. I think it would be nice to be able to specify more than one argument for `--color` option.

**Comment by actionless** [comment]
also i see stuff wasn't merged properly, for example diff to `change_color.sh` is the same as latest commits to master branch but being added as new commits

**Comment by n3oxmind** [comment]
I already reviewed your ./install.sh script, and I don't mind to help you improve it but we will end up having the same ./install.sh I've already wrote. 
using functions will allow you to control the flow of the script and help you develop each part of your script much easier and without effecting the  rest of the code.
also function will allow you to parse user inputs (command line arguments) and validate them and prevent the other invalid arguments from being processed. 
THE most important thing is to make sure your script is safe to use (and you should consider every possibility that could break the script). In your script I don't see anything that will validate the user input.

**Comment by n3oxmind** [comment]
@nana-4 
> Was it bad for you to simply improve my revised version? In my opinion, it is better and simpler to lump install items together as an function than to separate them
> 
I agree with simple but not better than functions. if you ask me to choose between security or simplicity I'll always go with security. functions is meant to simplify the coding.

**Comment by n3oxmind** [comment]
@nana-4,
I'm gonna review your code again, and comment on it.

**Comment by nana-4** [comment]
@actionless Exactly.

I guess this can be solved as follows (@n3oxmind, please try this):
```bash
cd materia-theme
git remote add upstream https://github.com/nana-4/materia-theme.git
git fetch upstream
git merge upstream/master
git checkout --ours install.sh
git add .
git commit
# then type :wq and hit Enter
git push origin master
```
@n3oxmind 

To be honest, I don't quite understand security. In the case of my script, what kind of security risk do we have?

> also function will allow you to parse user inputs (command line arguments) and validate them and prevent the other invalid arguments from being processed.

Hmm, I'm not very sure, but my script already prevents the other invalid arguments from being processed, doesn't it?

**Comment by n3oxmind** [comment]
Since your new `/.install.sh` script does the same thing. I'm going to close this PR.

**Comment by nana-4** [comment]
@n3oxmind I'm sorry for my lack of explanation.
Anyway I'll fix `install.sh` as you pointed out and push it to `master`. Thanks.

**Pull request closed without merging**
