### PR TITLE
Scripting rework for sanity and safety

### PR DESCRIPTION
**Pull request by TiZ-EX1**
Hi there. I know this is a pretty big pull request, sorry about this.

The first thing I did was remove hardcoded paths to inkscape and optipng. Don't hardcode paths to needed programs.

But after that, I went on a huge-ass script cleanup, because I saw *a lot of things bothering me*. The end goal was to have every last script pass shellcheck.

The first and most important thing I did is quoted every variable substitution to ensure that spaces don't gunk up the works. I saw there was a lot of use of the curly braces, eg `${whatever}`. That's not a substitute for quoting variables. In fact, it's entirely unnecessary *unless* you're doing array access, some sort of special expansion like accounting for a variable that might be unset, or sticking a variable in front of [A-z0-9_]. Like, `${num}th` or something like that. **Line 49 of test.sh was definitely going to cause someone serious trouble someday if not properly quoted.**

The *only* time you don't need to quote variables is during assignment. Assignment styles are inconsistent right now, but that doesn't really hurt things so I'm leaving it like that for now.

One other gotcha is stuff like `{scss,css}`. To make that work with quoted vars, you have to stick that portion *outside* of the quotes, but *still touching*. If a non-quoted section is touching a quoted section, they're considered the same parameter. You can use this for stuff like `get_money '$USD'"$amt"`.

There were a few times that a variable was used to hold command line args. I changed those uses to an array, and quoted them properly. In the render assets scripts, I used some strange-looking syntax; basically an empty array is considered an unset variable and attempting to quote it will make it fail, so that syntax is to get around that.

Speaking of arrays... `LATEST_GS_VERSION=${GS_VERSIONS[@]: -1}` is entirely wrong; you want `${GS_VERSIONS[-1]}`. There were a few places where braces weren't even used for array access, and they *are required*.

I changed the render-assets scripts up quite a bit. With `xargs -n1`, you don't even really need to treat it differently than how you would invoke GNU parallel. So all that does now is determine which one to do. I got rid of redundant duplication between the light and dark in gtk2, and instead use a parameter to determine which assets to make.

Another thing I did was change `echo "$var" | cmd` to `cmd <<< "$var"`. It's clearer, more idiomatic, and doesn't make a pipe.

There were a bunch of other little things I did to make things clearer or otherwise more idiomatic. I did `set -ueo pipefail` on pretty much every script. It's better for a script to fail than for it to break something.

Please let me know if there's anything in particular you need changed or anything that broke as a result. I tested as much as I could but I could have missed something.

### CODE REVIEW

**Comment by TiZ-EX1** [comment]
Yep, still works with oomox.

**Comment by nana-4** [comment]
Amazing job! I'm very amateur of shell script, so this rework is very helpful for me 😆

Thanks a lot @TiZ-EX1!

Also thanks @actionless for your reviewing :)

**Comment by TiZ-EX1** [comment]
Thank you very much, good working with you.

**Comment by svnset** [comment]
@TiZ-EX1 Nice work. Thanks from me as well :)

**Pull request merged**
