### PR TITLE
Cinnamon Theme - Initial Commit

### PR DESCRIPTION
**Pull request by smurphos**
#232 
@actionless @nana-4 

Hi,

Well that was an interesting exercise - learnt a few more things about Cinnamon theming, uncovered a few more Cinnamon bugs and gave myself a 101 in box_shadows. Anyway theme is ready for review. I'm pretty pleased overall.

A couple of technical notes - the panel uses panel_bg_color. To ensure that the theme works well in Oomox as-well as in the Materia varieties I needed to use the various titlebar_fg_colors for panel foreground elements. As a result I also had to leave the Materia-Light variants of Cinnamon as using Titlebar 'dark' to build the Cinnamon theme. 

I've made a few animated gif screencasts to demo - testing Byzanz as a straight to gif screenrecorder. It's not bad but there are a few artifacts in the output that don't reflect what the theme looks like on screen. 

Hope you like.... ;-)

Materia
screencast-2018-04-10-081455

Materia Dark
screencast-2018-04-10-081650

Materia Clearlooks
screencast-2018-04-10-082004

Materia Kashmir-Blue
screencast-2018-04-10-082216

### CODE REVIEW

**Comment by smurphos** [comment]
Apologies for the additional commits - a few usability issues highlighted with a couple of days of use of the theme - if you want them squashed please let me know.

**Comment by nana-4** [comment]
Great job! :tada: Thank you very much for your hard work! Overall it looks very nice :)

Well, I should have said this first when you kindly contacted me (sorry), but my current bigger requests are:

1. I'd prefer **2** spaces for the SCSS indentation as other `.scss` files do. Could you change the indentation from 4 to 2? :)
2. I'd prefer to unify the _section_ files (`src/_sass/cinnamon/sections/*.scss`) as `src/_sass/cinnamon/_common.scss` in order to _easily_ follow the upstream changes. (Please refer to the `gnome-shell` [common file](https://github.com/nana-4/materia-theme/blob/master/src/_sass/gnome-shell/_common-3.28.scss).) To me, it would be hard to compare the original **[one file](https://github.com/linuxmint/Cinnamon/blob/master/data/theme/cinnamon.css)** and the current **split files**. Would you mind unifying the split files as `_common.scss` and sort the classes as with the upstream `cinnamon.css`?

> Apologies for the additional commits

No need to apologize. :smile:  I'm also sorry for the late reply. 😜

**Comment by smurphos** [comment]
Will do - would you like the _extends incorporated into _common as-well or keep them as a separate import?

**Comment by smurphos** [comment]
Thank-you. All good to merge from my point of view.

Hopefully the mint team will convert the default theme at some point. The newish Mint-Y theme is built with sass so they should be open to it. But I'll pencil it into my possible projects list in any case...

**Comment by nana-4** [comment]
Glad to hear that. Thank you!

**Comment by actionless** [comment]
i think after few more iterations of improving it you could propose it upstream, since the theme is very configurable so they could shape/color it whatever they want by default

**Pull request merged**
