### PR TITLE
feat(change_color, *: render-assets): add FORCE_INKSCAPE env var

### PR DESCRIPTION
**Pull request by actionless**
related to #523

### CODE REVIEW

**Comment by nana-4** [comment]
Thanks for the PR :)

Do we need `{}` on those variables? I read somewhere that `""` should always have, but `{}` isn't necessarily needed.

Other than that, LGTM :+1:

**Comment by actionless** [comment]
> "$EXPORT_FILE_OPTION"="$ASSETS_DIR/$i.png"

this one was making `shellcheck` unhappy, so i decided also to change the rest to be in the same style

**Comment by nana-4** [comment]
Ah, I see. According to https://github.com/koalaman/shellcheck/wiki/SC2140, it seems enough to just remove the double quotes in the middle:

```sh
"$EXPORT_FILE_OPTION=$ASSETS_DIR/$i.png"
```

Could you please update those variables not to add `{}`?

**Comment by actionless** [comment]
@nana-4 removed

**Comment by nana-4** [comment]
LGTM. Thanks a lot!

**Pull request merged**
